name: Remove out of date container packages

on:
  schedule:
    - cron:  "0 */8 * * *"
  workflow_dispatch:

jobs:
  delete-package-versions:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        package:
          - "alpine"
          - "alpine-s6"
          - "debian"
          - "debian-s6"
          - "apache"
          - "apache-php"
          - "aspnet"
          - "busybox"
          - "ccf"
          - "clamav"
          - "ftps"
          - "freescout"
          - "freshrss"
          - "mariadb"
          - "mileage"
          - "nginx"
          - "nginx-php"
          - "nginx-proxy"
          - "nginx-webdav"
          - "node"
          - "ocis"
          - "php"
          - "postgresql"
          - "redis"
          - "samba"
          - "send"
          - "wordpress"
          - "backup"
          - "pg-upgrade"
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.package }}
          package-type: "container"
          min-versions-to-keep: 100
          token: ${{ secrets.PAT_MANAGE_PACKAGES }}
#  delete-old-packages:
#    runs-on: ubuntu-latest
#    continue-on-error: true
#    strategy:
#      max-parallel: 4
#      matrix:
#        package:
#          - "dnscrypt-proxy"
#          - "zabbix"
#    steps:
#      - uses: actions/delete-package-versions@v4
#        with:
#          package-name: ${{ matrix.package }}
#          package-type: "container"
#          min-versions-to-keep: 0
#          token: ${{ secrets.PAT_MANAGE_PACKAGES }}
